---
- name: Ensure oci oss bucket exists
  command: oci os bucket get --name {{ artifacts_container }}

- name: Upload folder to oci oss bucket
  command: oci os object bulk-upload -bn {{ artifacts_container }} --prefix {{destination_path}} --src-dir {{ source_path }} --content-type auto --overwrite
  async: 3600
  poll: 10 