- hosts: local
  become: yes
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
    OCI_CLI_AUTH: "instance_principal" 
  tasks:
    - name: rename env_domain in preview_cdn.html for CDN
      shell: |
        echo "{{sunbird_portal_preview_cdn_url}}"
        sed -i 's|cdn_url|{{sunbird_portal_preview_cdn_url}}|g' "{{currentws}}"/ansible/preview/preview_cdn.html
      when: sunbird_portal_preview_cdn_url is defined
      tags:
        - preview

    - name: set common oci variables
      set_fact:
        oss_bucket_name: "{{ plugin_container_name }}"
        oss_namespace: "{{ oci_namespace }}"
      tags:
        - always

    - name: delete files and folders from oci oss
      include_role:
        name: oci-cloud-storage
        apply:
         environment:
          OCI_CLI_AUTH: "instance_principal"  
        tasks_from: delete-folder.yml
      vars:
          oss_path: "{{ folder_name }}/"
      tags:
        - content-editor
        - collection-editor
        - generic-editor
        - preview

    - name: upload batch to oci oss
      include_role:
        name: oci-cloud-storage
        apply:
         environment:
          OCI_CLI_AUTH: "instance_principal"  
        tasks_from: upload-folder.yml
      vars:
        oss_path: "{{ folder_name }}/"
        local_file_or_folder_path: "{{ source_name }}"
      tags:
        - content-editor 
        - collection-editor
        - generic-editor
        - preview
        - editor
        - core-plugins  

    - name: upload file to oci oss
      include_role:
        name: oci-cloud-storage
        apply:
         environment:
          OCI_CLI_AUTH: "instance_principal"  
        tasks_from: upload.yml
      vars:
        oss_path: "artefacts/content-player/content-player-{{ player_version_number }}.zip"
        local_file_or_folder_path: "{{ source_file_name }}"
      tags:
        - preview

    - name:  run az_copy.sh
      shell: "bash {{ az_file_path }} {{ plugin_container_name }} {{ source_file }}"
      async: 3600
      poll: 10
      tags:
        - plugins

    # - name: delete and re-upload plugins for oci
    #   include_role:
    #     name: oci-cloud-storage
    #     apply:
    #      environment:
    #       OCI_CLI_AUTH: "instance_principal"  
    #     tasks_from: "{{ item[0] }}"
    #   vars:
    #     object_prefix: "content-plugins/{{ item[1] }}/"
    #     local_file_or_folder_path: "{{ source_folder }}/{{ item[1] }}"
    #   with_nested:
    #     - ['oss-delete-batch-no-poll.yml', 'oss-upload-batch-no-poll.yml']
    #     - "{{ lookup('file', plugins_to_delete_and_upload).split('\n') }}"
    #   tags:
    #     - plugins