- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  vars:
    artifacts_container: "{{desktop_container}}"
    artifact: "{{destination_path}}"
    artifact_path: "{{playbook_dir}}/../{{src_file_path}}"
  environment:
    OCI_CLI_AUTH: "instance_principal"
  roles:
    - artifacts-upload-oci
  tags:
    - upload-desktop-faq
 
 
- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  vars:
    artifacts_container: "{{desktop_container}}"
    artifact: "{{destination_path}}"
    artifact_path: "{{playbook_dir}}/../{{src_file_path}}"
  environment:
    OCI_CLI_AUTH: "instance_principal"
  roles:
    - artifacts-upload-oci
  tags:
    - upload-label

- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  vars:
    source_path: "{{playbook_dir}}/../{{src_file_path}}"
    destination_path: "{{destination_path}}"
    container_name: "{{desktop_container}}"
  environment:
    OCI_CLI_AUTH: "instance_principal"
  roles:
    - upload-batch
  tags:
    - upload-chatbot-config
    - upload-batch
