- hosts: local
  become: yes
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
        AZURE_STORAGE_ACCOUNT: "{{ sunbird_public_storage_account_name }}"
        AZURE_STORAGE_SAS_TOKEN: "{{ sunbird_public_storage_account_sas }}"
        OCI_CLI_AUTH: "instance_principal"
  tasks:
    - name: Create directories
      file:
        path: dial_schema_template_files/{{ item.path }}
        state: directory
        owner: jenkins
        group: jenkins
      with_filetree: "{{ source_name }}"
      when: item.state == 'directory'

    - name: Template files in all directories
      template:
        src: "{{ item.src }}"
        dest: dial_schema_template_files/{{ item.path }}
      with_filetree: "{{ source_name }}"
      when: item.state == 'file'
            
    # - name: upload batch
    #   command: "az storage blob upload-batch --destination {{ dial_plugin_container_name }}/schemas/local --source dial_schema_template_files"
    #   async: 3600
    #   poll: 10

    - name: upload batch to oci oss bucket
      command: oci os object bulk-upload -bn {{ dial_plugin_container_name }} --prefix {{ dial_plugin_container_name }}/schemas/local --src-dir dial_schema_template_files --content-type auto --overwrite
      async: 3600
      poll: 10 