- hosts: local
  become: yes
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
    OCI_CLI_AUTH: "instance_principal"
  tasks:
    - name: upload batch to oci oss bucket
      command: oci os object bulk-upload -bn {{ plugin_container_name }} --prefix schemas/local --src-dir {{ source_name }} --content-type auto --overwrite
      async: 3600
      poll: 10 