- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  vars:
    container_name: "{{ blob_container }}"
    destination_path: "{{ blob_container }}"
  environment:
    OCI_CLI_AUTH: "instance_principal"
  tasks:
    - name: upload files
      include_role:
        name: upload-batch
      vars:
        source_path: "{{ playbook_dir }}/../utils/{{ item }}"
      with_items:
        - "{{ source_folder.split(',') }}"
  tags:
    - upload-faqs
